import os
import cons

Import('env')
env = env.Clone()

env.IncludeHDF5()
env.Append(LIBS = ['winmm', 'comctl32', 'rpcrt4', 'wsock32', 'wininet', 'kernel32', 'user32', 'gdi32', 'winspool', 'version'])
env.Append(LIBS = ['comdlg32', 'advapi32', 'shell32', 'ole32', 'oleaut32', 'uuid', 'odbc32', 'odbccp32', 'shlwapi'])
env.Append(CPPDEFINES = ['_WINDOWS', '_UNICODE', 'UNICODE'])
env.Append(LINKFLAGS = [r'/SUBSYSTEM:CONSOLE', r'/MACHINE:X64', r'/MANIFEST'])

test = env.Program(target="test", source=Glob("*.cpp"))
test_install = env.Install('#', test)

Return('test', 'test_install')