$env:VCPKG_DIR=$env:VCPKG_ROOT_DIR + "/installed/x64-windows"
$env:CTF=$env:VCPKG_ROOT_DIR + "/scripts/buildsystems/vcpkg.cmake"
$env:IDIR=$env:SPAM_ROOT_DIR + "/install/opencv"
$env:HDIR=$env:SPAM_ROOT_DIR + "/3rdparty/opencv"
$env:BDIR=$env:SPAM_ROOT_DIR + "/build/opencv/msvs"
$env:EXDIR=$env:SPAM_ROOT_DIR + "/apex/modules"
$env:CAF=$env:SPAM_ROOT_DIR + "/3rdparty/cmake/opencv.cmake"

cmake --no-warn-unused-cli `
    -DCMAKE_TOOLCHAIN_FILE:STRING=$env:CTF `
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=FALSE `
    -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
    -DCMAKE_SKIP_RPATH:BOOL=FALSE `
    -DCMAKE_SKIP_INSTALL_RPATH:BOOL=FALSE `
    -DCMAKE_MINSIZEREL_POSTFIX:STRING=_minsize `
    -DCMAKE_RELWITHDEBINFO_POSTFIX:STRING=_debinfo `
    -DMIN_VER_CMAKE:STRING=3.15 `
    -DBUILD_DOCS:BOOL=FALSE `
    -DBUILD_TESTS:BOOL=FALSE `
    -DBUILD_PERF_TESTS:BOOL=FALSE `
    -DBUILD_WITH_STATIC_CRT:BOOL=FALSE `
    -DBUILD_WITH_DEBUG_INFO:BOOL=TRUE `
    -DBUILD_JASPER:BOOL=TRUE `
    -DBUILD_JPEG:BOOL=TRUE `
    -DBUILD_OPENEXR:BOOL=TRUE `
    -DBUILD_PNG:BOOL=TRUE `
    -DBUILD_TIFF:BOOL=TRUE `
    -DBUILD_WEBP:BOOL=TRUE `
    -DBUILD_ZLIB:BOOL=TRUE `
    -DBUILD_TBB:BOOL=FALSE `
    -DBUILD_PROTOBUF:BOOL=TRUE `
    -DBUILD_opencv_apps:BOOL=FALSE `
    -DBUILD_opencv_java:BOOL=FALSE `
    -DBUILD_opencv_js:BOOL=FALSE `
    -DBUILD_ANDROID_PROJECT:BOOL=FALSE `
    -DBUILD_ANDROID_EXAMPLES:BOOL=FALSE `
    -DBUILD_PACKAGE:BOOL=FALSE `
    -DBUILD_JAVA:BOOL=FALSE `
    -DPROTOBUF_UPDATE_FILES:BOOL=FALSE `
    -DUPDATE_PROTO_FILES:BOOL=FALSE `
    -DENABLE_PYLINT:BOOL=FALSE `
    -DENABLE_FLAKE8:BOOL=FALSE `
    -DENABLE_CXX11:BOOL=TRUE `
    -DWITH_OPENMP:BOOL=TRUE `
    -DWITH_TBB:BOOL=TRUE `
    -DWITH_Eigen3:BOOL=TRUE `
    -DWITH_VTK:BOOL=FALSE `
    -DWITH_GTK:BOOL=FALSE `
    -DWITH_PROTOBUF:BOOL=TRUE `
    -DWITH_OPENJPEG:BOOL=FALSE `
    -DWITH_LAPACK:BOOL=FALSE `
    -DBUILD_EXAMPLES:BOOL=FALSE `
    -DBUILD_opencv_legacy:BOOL=FALSE `
    -DBUILD_NEW_PYTHON_SUPPORT:BOOL=TRUE `
    -DBUILD_opencv_python2:BOOL=FALSE `
    -DBUILD_opencv_python3:BOOL=TRUE `
    -DBUILD_opencv_dnn:BOOL=FALSE `
    -DBUILD_opencv_ovis:BOOL=FALSE `
    -DBUILD_opencv_quality:BOOL=FALSE `
    -DBUILD_opencv_rgbd:BOOL=FALSE `
    -DOPENCV_BIN_INSTALL_PATH:STRING=bin `
    -DOPENCV_INCLUDE_INSTALL_PATH:STRING=include `
    -DOPENCV_LIB_INSTALL_PATH:STRING=lib `
    -DOPENCV_3P_LIB_INSTALL_PATH:STRING=lib `
    -DCMAKE_CXX_STANDARD:STRING=17 `
    -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=TRUE `
    -DCMAKE_CXX_EXTENSIONS:BOOL=FALSE `
    -DCMAKE_DISABLE_FIND_PACKAGE_Git:BOOL=TRUE `
    -DCMAKE_DISABLE_FIND_PACKAGE_JNI:BOOL=TRUE `
    -DOPENCV_SKIP_PYTHON_LOADER:BOOL=FALSE `
    -DOPENCV_EXTRA_MODULES_PATH:STRING=$env:EXDIR `
    -DCMAKE_INSTALL_PREFIX:STRING=$env:IDIR `
    -C $env:CAF `
    -S $env:HDIR `
    -B $env:BDIR `
    -G"Visual Studio 15 2017 Win64"

cmake --open $env:BDIR
