#ifndef SPAM_UI_ERROR_DEFINE_H
#define SPAM_UI_ERROR_DEFINE_H

enum class SpamResult
{
    kSR_SUCCESS,
    kSR_OK = kSR_SUCCESS,
    kSR_SUCCESS_NOOP,
    kSR_IMG_EMPTY,
    kSR_IMG_TYPE_NOT_SUPPORTED,
    kSR_IMG_CORRUPTED,
    kSR_TM_EMPTY_TEMPL_REGION,
    kSR_TM_TEMPL_REGION_TOO_SMALL,
    kSR_TM_TEMPL_REGION_TOO_LARGE,
    kSR_TM_TEMPL_REGION_OUT_OF_RANGE,
    kSR_TM_TEMPL_INSIGNIFICANT,
    kSR_TM_PYRAMID_LEVEL_INVALID,
    kSR_TM_PYRAMID_LEVEL_TOO_LARGE,
    kSR_TM_ANGLE_RANGE_INVALID,
    kSR_TM_CORRUPTED_TEMPL_DATA,
    kSR_TM_INSTANCE_NOT_FOUND,
    kSR_ERROR,
    kSR_FAILURE = kSR_ERROR
};

#endif //SPAM_UI_ERROR_DEFINE_H