# coding: utf-8
# This file is automatically generated by MSC Apex Iberian Lynx Feature Pack 1 PRE Build CLR:644560

# The sole purpose of this file is to automatically recover a model to its last
# state prior to an unexpected termination of the application.
# This file is not a session file nor does it contain supported scripting APIs.
# This recovery file contains syntax that must not be edited.

import SCA
from MSC.Scripting.Commands import (_PIEx, _SCAEx, _SP, _EntityList)
from MSC.Scripting.Aliases  import *

ROOTMGR = _SP(SCA.getService('msc.apex.appfw.EntityFW', 'msc.apex.appfw.IRootManager'))
SCA.loadTypes("msc", 1) 
import msc
UNITMGR = _SP(SCA.getService('msc.apex.appfw.Units', 'msc.apex.appfw.IUnits'))
UNITMGR.setCurrentUnitSystem(r'''mm-kg-s-N''')

def getConnMesh(meshName):
    meshEnt          = ROOTMGR.getByFullName(meshName)
    ret, ifMeshGroup = meshEnt.getInterface("msc.apex.plugin.fem.IPFWSupport")
    ifPFWObj         = ifMeshGroup.getPFWIPO()
    ret, ifConnMesh  = ifPFWObj.getInterface("SCA.PersistenceFW.CAEData.IContinuousMesh")
    return ifConnMesh

def getMeshPart(connMesh):
    ret, meshBody = connMesh.getParent()
    ret, meshPart = meshBody.getParent()
    ret, meshPart  = meshPart.getInterface("SCA.PersistenceFW.CAEData.IMeshPart")
    return meshPart

def getElement(meshPart, elemid):
    ret, spElement = meshPart.getElementById(elemid, False)
    return spElement

def getMeshByElement(spElement):
    ret, spMesh = spElement.getMesh()
    return spMesh

def getMeshId(spMesh):
    ret, meshId = spMesh.getId()
    return meshId

def getFEMService():
    return _SP(SCA.getService('msc.apex.plugin.fem.FEMService', 'msc.apex.plugin.fem.SCAIFEMService'))

connMesh = getConnMesh(r'/Model Files/Root Assembly/Part 1/Mesh 2')
meshPart = getMeshPart(connMesh)
femSrv   = getFEMService()
femSrv.clearEphemeral1DMeshOnOriginalTieEdge()
spElem   = getElement(meshPart, 229)
spMesh   = getMeshByElement(spElem)
print(getMeshId(spMesh))