$env:VCPKG_DIR=$env:VCPKG_ROOT_DIR + "/installed/x64-windows"
$env:CTF=$env:VCPKG_ROOT_DIR + "/scripts/buildsystems/vcpkg.cmake"
$env:IDIR=$env:SPAM_ROOT_DIR + "/occt/install"
$env:HDIR=$env:SPAM_ROOT_DIR + "/occt"
$env:BDIR=$env:SPAM_ROOT_DIR + "/occt/msvs"
$env:VTKINSTALLDIR=$env:SPAM_ROOT_DIR + "/VTK/install"
$env:VTKINCLUDEDIR=$env:SPAM_ROOT_DIR + "/VTK/install/include/vtk-9.0"

cmake --no-warn-unused-cli `
    -DCMAKE_TOOLCHAIN_FILE:STRING=$env:CTF `
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=FALSE `
    -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
    -DCMAKE_SKIP_RPATH:BOOL=FALSE `
    -DCMAKE_SKIP_INSTALL_RPATH:BOOL=FALSE `
    -DCMAKE_MINSIZEREL_POSTFIX:STRING=_minsize `
    -DCMAKE_RELWITHDEBINFO_POSTFIX:STRING=_debinfo `
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=TRUE `
    -DBUILD_DOC_Overview:STRING=OFF `
    -DBUILD_SAMPLES_QT:STRING=OFF `
    -DBUILD_SAMPLES_MFC:STRING=OFF `
    -DBUILD_MODULE_Draw:STRING=OFF `
    -DINSTALL_TEST_CASES:STRING=OFF `
    -DINSTALL_SAMPLES:STRING=OFF `
    -DUSE_TBB:STRING=OFF `
    -DUSE_FREEIMAGE:STRING=OFF `
    -DUSE_FREETYPE:STRING=OFF `
    -DUSE_VTK:STRING=ON `
    -D3RDPARTY_VTK_DIR:STRING=$env:VTKINSTALLDIR `
    -D3RDPARTY_VTK_INCLUDE_DIR:STRING=$env:VTKINCLUDEDIR `
    -DCMAKE_BUILD_TYPE:STRING=Debug `
    -DCMAKE_INSTALL_PREFIX:STRING=$env:IDIR `
    -S $env:HDIR `
    -B $env:BDIR `
    -G"Visual Studio 15 2017 Win64"
