find_path(GLIB_INCLUDE_DIR NAMES "glib.h" DOC "Glib include directory")

find_library(GLIB_glib_LIBRARY_RELEASE NAMES "glib-2.0" DOC "glib library release (potentially the C library)")
find_library(GLIB_glib_LIBRARY_DEBUG NAMES "glib-2.0d" DOC "glib library debug (potentially the C library)")
find_program(GLIB_glib_RUNTIME_LIBRARY_RELEASE "glib-2.dll" PATH_SUFFIXES bin DOC "glib library release (potentially the C library)")
find_program(GLIB_glib_RUNTIME_LIBRARY_DEBUG "glib-2d.dll" PATH_SUFFIXES bin DOC "glib library release (potentially the C library)")

find_library(GLIB_gio_LIBRARY_RELEASE NAMES "gio-2.0" DOC "gio library release (potentially the C library)")
find_library(GLIB_gio_LIBRARY_DEBUG NAMES "gio-2.0d" DOC "gio library debug (potentially the C library)")
find_program(GLIB_gio_RUNTIME_LIBRARY_RELEASE "gio-2.dll" PATH_SUFFIXES bin DOC "gio library release (potentially the C library)")
find_program(GLIB_gio_RUNTIME_LIBRARY_DEBUG "gio-2d.dll" PATH_SUFFIXES bin DOC "gio library release (potentially the C library)")

find_library(GLIB_gmodule_LIBRARY_RELEASE NAMES "gmodule-2.0" DOC "gmodule library release (potentially the C library)")
find_library(GLIB_gmodule_LIBRARY_DEBUG NAMES "gmodule-2.0d" DOC "gmodule library debug (potentially the C library)")
find_program(GLIB_gmodule_RUNTIME_LIBRARY_RELEASE "gmodule-2.dll" PATH_SUFFIXES bin DOC "gmodule library release (potentially the C library)")
find_program(GLIB_gmodule_RUNTIME_LIBRARY_DEBUG "gmodule-2d.dll" PATH_SUFFIXES bin DOC "gmodule library release (potentially the C library)")

find_library(GLIB_gobject_LIBRARY_RELEASE NAMES "gobject-2.0" DOC "gobject library release (potentially the C library)")
find_library(GLIB_gobject_LIBRARY_DEBUG NAMES "gobject-2.0d" DOC "gobject library debug (potentially the C library)")
find_program(GLIB_gobject_RUNTIME_LIBRARY_RELEASE "gobject-2.dll" PATH_SUFFIXES bin DOC "gobject library release (potentially the C library)")
find_program(GLIB_gobject_RUNTIME_LIBRARY_DEBUG "gobject-2d.dll" PATH_SUFFIXES bin DOC "gobject library release (potentially the C library)")

find_library(GLIB_gthread_LIBRARY_RELEASE NAMES "gthread-2.0" DOC "gthread library release (potentially the C library)")
find_library(GLIB_gthread_LIBRARY_DEBUG NAMES "gthread-2.0d" DOC "gthread library debug (potentially the C library)")
find_program(GLIB_gthread_RUNTIME_LIBRARY_RELEASE "gthread-2.dll" PATH_SUFFIXES bin DOC "gthread library release (potentially the C library)")
find_program(GLIB_gthread_RUNTIME_LIBRARY_DEBUG "gthread-2d.dll" PATH_SUFFIXES bin DOC "gthread library release (potentially the C library)")

include(SelectLibraryConfigurations)
select_library_configurations(GLIB_glib)
select_library_configurations(GLIB_gio)
select_library_configurations(GLIB_gmodule)
select_library_configurations(GLIB_gobject)
select_library_configurations(GLIB_gthread)
select_library_configurations(GLIB_glib_RUNTIME)
select_library_configurations(GLIB_gio_RUNTIME)
select_library_configurations(GLIB_gmodule_RUNTIME)
select_library_configurations(GLIB_gobject_RUNTIME)
select_library_configurations(GLIB_gthread_RUNTIME)

mark_as_advanced(GLIB_INCLUDE_DIR)
mark_as_advanced(GLIB_glib_LIBRARY)
mark_as_advanced(GLIB_gio_LIBRARY)
mark_as_advanced(GLIB_gmodule_LIBRARY)
mark_as_advanced(GLIB_gobject_LIBRARY)
mark_as_advanced(GLIB_gthread_LIBRARY)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLIB FOUND_VAR GLIB_FOUND REQUIRED_VARS GLIB_glib_LIBRARY GLIB_gio_LIBRARY GLIB_gmodule_LIBRARY GLIB_gobject_LIBRARY GLIB_gthread_LIBRARY GLIB_INCLUDE_DIR)

include(SpamCommon)
if(GLIB_FOUND)
  set(GLIB_INCLUDE_DIRS "${GLIB_INCLUDE_DIR}")
  set(GLIB_LIBRARIES "${GLIB_glib_LIBRARY}" "${GLIB_gio_LIBRARY}" "${GLIB_gmodule_LIBRARY}" "${GLIB_gobject_LIBRARY}" "${GLIB_gthread_LIBRARY}")
  spam_export_shared_pack_component(GLIB glib)
  spam_export_shared_pack_component(GLIB gio)
  spam_export_shared_pack_component(GLIB gmodule)
  spam_export_shared_pack_component(GLIB gobject)
  spam_export_shared_pack_component(GLIB gthread)
  #set_target_properties(FFI::FFI PROPERTIES INTERFACE_COMPILE_DEFINITIONS FFI_BUILDING)
  set(GLIB_LIBRARY ${GLIB_glib_LIBRARY})
  set(GLIB_LIBRARY_DEBUG ${GLIB_glib_LIBRARY_DEBUG})
  set(GLIB_LIBRARY_RELEASE ${GLIB_glib_LIBRARY_RELEASE})
  set(GIO_LIBRARY ${GLIB_gio_LIBRARY})
  set(GIO_LIBRARY_DEBUG ${GLIB_gio_LIBRARY_DEBUG})
  set(GIO_LIBRARY_RELEASE ${GLIB_gio_LIBRARY_RELEASE})
  set(GMODULE_LIBRARY ${GLIB_gmodule_LIBRARY})
  set(GMODULE_LIBRARY_DEBUG ${GLIB_gmodule_LIBRARY_DEBUG})
  set(GMODULE_LIBRARY_RELEASE ${GLIB_gmodule_LIBRARY_RELEASE})
  set(GOBJECT_LIBRARY ${GLIB_gobject_LIBRARY})
  set(GOBJECT_LIBRARY_DEBUG ${GLIB_gobject_LIBRARY_DEBUG})
  set(GOBJECT_LIBRARY_RELEASE ${GLIB_gobject_LIBRARY_RELEASE})
  set(GTHREAD_LIBRARY ${GLIB_gthread_LIBRARY})
  set(GTHREAD_LIBRARY_DEBUG ${GLIB_gthread_LIBRARY_DEBUG})
  set(GTHREAD_LIBRARY_RELEASE ${GLIB_gthread_LIBRARY_RELEASE})
endif()
