Import('env')
env = env.Clone()

env.Append(CPPDEFINES = ['_WINDOWS', '_UNICODE', 'UNICODE'])
env.Append(LINKFLAGS = [r'/SUBSYSTEM:WINDOWS', r'/MACHINE:X64', r'/MANIFEST'])
env.IncludeTBB()
env.IncludePython2()

swig = Environment(tools=['swig'], SWIG=r'D:\Data\swigwin-3.0.12\swig.exe')
swig.AppendUnique(SWIGFLAGS=['-c++', '-python'])
swig.Replace(SWIGCXXFILESUFFIX=['_wrap.cpp'])

#print("SWIGCFILESUFFIX is: %s" % swig.subst('$SWIGCFILESUFFIX'))
#print("SWIGCOM is: %s" % swig.subst('$SWIGCOM'))
#print("SWIGCOMSTR is: %s" % swig['SWIGCOMSTR'])
#print("SWIGCXXFILESUFFIX is: %s" % swig.subst('$SWIGCXXFILESUFFIX'))
#print("SWIGFLAGS is: %s" % swig.subst('$SWIGFLAGS'))
#print("_SWIGINCFLAGS is: %s" % swig.subst('$_SWIGINCFLAGS'))
#print("SWIGINCPREFIX is: %s" % swig.subst('$SWIGINCPREFIX'))
#print("SWIGOUTDIR is: %s" % swig['SWIGOUTDIR'])
#print("SWIGVERSION is: %s" % swig.subst('$SWIGVERSION'))
#print("SWIGPATH is: %s" % swig.subst('$SWIGPATH'))

apueWrap = swig.CXXFile(source = 'apue.i')
apuePyd = env.SharedLibrary(target="_apue", SHLIBSUFFIX='.pyd', source=Glob("*.cpp"))
Depends(apuePyd, apueWrap)

pyd_install = env.Install('#', apuePyd)
py_install = swig.Install('#', apueWrap)

Return('apuePyd', 'pyd_install', 'py_install')